-- #######################
-- Exercice 1
-- #######################
SELECT INDIVIDU.NOM, INDIVIDU.PRENOM
FROM INDIVIDU
INNER JOIN LOGEMENT ON INDIVIDU.N_LOGEMENT = LOGEMENT.N_LOGEMENT
INNER JOIN QUARTIER ON LOGEMENT.ID_QUARTIER = QUARTIER.ID_QUARTIER
INNER JOIN COMMUNE ON QUARTIER.ID_COMMUNE = COMMUNE.ID_COMMUNE
WHERE LOGEMENT.SUPERFICIE > 90 AND COMMUNE.NOM_COMMUNE = 'RUMILLY';


-- #######################
-- Exercice 2
-- #######################
UPDATE COMMUNE
SET NOMBRE_D_HABITANTS = 60000
WHERE NOM_COMMUNE = 'ANNECY';